### ISSUE TITLE
Add full details to curent Dashboard 

### ISSUE THREAD

**Issue by 100xA** [100xA/IntegrationFlutterApp#1]
<img width="403" alt="image" src="https://user-images.githubusercontent.com/24482713/226640598-c6c26f5c-8ade-4283-b453-2cb8b3c226ca.png">
Add details to current "Dashboard" so that "Maschinen" Page is obsolete

**Comment by randums** [comment]
Maschine 1: Abkantpresse
![Abkantpresse](https://github.com/100xA/IntegrationFlutterApp/assets/82224163/f8580f7f-6a55-4155-a14c-026cbf0167fb)
---------------------------------------------
Name: Trumpf - EHT TrumaBend S 85 - 25
Art: Hydraulische Abkantpresse
Nummer:  S 85 - 25
Kaufdatum: 2005
Letze Instandhaltung: 20.09.2022
Standort: Halle 1

**Comment by randums** [comment]
Maschine 2: Stanz Nippel Maschine
![Stanz Nippel Maschine](https://github.com/100xA/IntegrationFlutterApp/assets/82224163/6847e81d-b13e-4e8e-bd5c-98b9b1fe6d32)
------------------------
Name: EUROMAC ZX 1000/30
Art: CNC Stanz- und Nibbelmaschine
Nummer: ZX 1000/30
Kaufdatum: 2009
Letze Instandhaltung: 20.09.2020
Standort: Halle 2

**Comment by 100xA** [comment]
<img width="438" alt="image" src="https://github.com/100xA/IntegrationFlutterApp/assets/24482713/b9de9cb9-2c12-4fff-a67f-2077d6f1e45c">
