### ISSUE TITLE
Add Storage / "Lager" Capabilities

### ISSUE THREAD

**Issue by 100xA** [100xA/IntegrationFlutterApp#2]
The Storage is a page where the user can access all parts of a machine. Through the button "Ersatzteile" he can access the parts of the particular machine. In the main navigation point "Übersicht Lager" the user gets access to all available parts (no initial filtering). The parts are stored withtin the database.

**Comment by 100xA** [comment]
<img width="403" alt="image" src="https://user-images.githubusercontent.com/24482713/226644445-cdd285df-ea5f-4374-a293-97ca59017d42.png">

**Comment by randums** [comment]
![Schraube M8x35mm](https://github.com/100xA/IntegrationFlutterApp/assets/82224163/8c9b54e3-c414-446e-be1a-cca646378dce)
![Unterlegscheiben DIN 125 Standard](https://github.com/100xA/IntegrationFlutterApp/assets/82224163/6e9ba4bd-61ea-4149-9204-34c712cabccb)
![Unterlegscheiben DIN 440 Standard](https://github.com/100xA/IntegrationFlutterApp/assets/82224163/62d6b6c9-5feb-4fa8-876f-aac139dfcc9a)
![Zahnrad](https://github.com/100xA/IntegrationFlutterApp/assets/82224163/9a7b5aa1-8833-48a2-8ace-d074ada69ff3)
![Sme-Schrauben-Element](https://github.com/100xA/IntegrationFlutterApp/assets/82224163/4687f04b-a492-4e7b-be1d-bdccb21dc2be)
![Befestigungsschiene](https://github.com/100xA/IntegrationFlutterApp/assets/82224163/92381c0a-e19f-4d7c-be8a-3378e03ea0c0)
![Kupplung, 16-32mm](https://github.com/100xA/IntegrationFlutterApp/assets/82224163/495a212b-b0b8-4003-9b19-a7960f4a7705)
![M8 Hülsen mit Spreizfunktion](https://github.com/100xA/IntegrationFlutterApp/assets/82224163/2de7edc3-ef7e-40b8-8572-6c96f3b87499)
![Metallplatte 195x85 mm](https://github.com/100xA/IntegrationFlutterApp/assets/82224163/f0e0b783-ce3c-4b18-81bb-fa685b0e1e81)
![Metallplatte mit Löchern 148x105mm](https://github.com/100xA/IntegrationFlutterApp/assets/82224163/7b009935-c414-419a-968d-d8ab5fd2a9f9)
![Metallverbundrohr PE-RT 16x2,0 5m_Stange](https://github.com/100xA/IntegrationFlutterApp/assets/82224163/b742db4e-3ed0-4252-a165-2080618119cc)
![Mutter M9x1,25, Höhe 5mm](https://github.com/100xA/IntegrationFlutterApp/assets/82224163/922e34eb-e97d-4753-a066-b053c9b6e1cd)
![Press-Übergangsnippel](https://github.com/100xA/IntegrationFlutterApp/assets/82224163/4fbe3b05-a365-415c-bd5d-d1a258fae2b4)
![RAVENOL Super HD 30 Öl](https://github.com/100xA/IntegrationFlutterApp/assets/82224163/d07c7b80-a1c2-4ddc-a0f2-d06e5ef70296)

**Comment by randums** [comment]
Beschriftung von Oben nach Unten: 
Schraube M8x35mm

Unterlegscheiben DIN 125 Standard

Unterlegscheiben DIN 440 Standard

Zahnrad

Sme-Schrauben-Element

Befestigungsschiene

Kupplung, 16-32mm

M8 Hülsen mit Spreizfunktion

Metallplatte 195x85 mm

Metallplatte mit Löchern 148x105mm

Metallverbundrohr PE-RT 16x2,0 5m_Stange

Mutter M9x1,25, Höhe 5mm

Press-Übergangsnippel

RAVENOL Super HD 30 Öl

**Comment by randums** [comment]
Zuteilung zu den Maschinen kann Radom sein, einf das wenn man nach einer Filtert ein paar angezeigt werden.
