### ISSUE TITLE
Change Profiles

### ISSUE THREAD

**Issue by 100xA** [100xA/IntegrationFlutterApp#3]
Change profiles localized  (just for show)
<img width="403" alt="image" src="https://user-images.githubusercontent.com/24482713/226645720-aeff22e5-42d4-45b7-9f3a-682daa2e6717.png">

**Comment by randums** [comment]
Ein Profil reicht an sich, wenn's Zeitlich klappt 2 Profile.
1. Profil: Normaler Benutzer, kann alle Buttons drücken und auch To-Do Listen ausfüllen usw. 
2. Profil: "Spectator", kann keine Buttons drücken sondern nur alles Anschauen. Bswp. die To-Do liste von dem Profil 1.

**Comment by randums** [comment]
Profil 1 Daten:
Vorname: Hanz
Nachname: Peter
Geburtstag: 23.04.1989
E-Mail: hanzpeter1989@gmail.com
Telefon Privat: 0168 / 49674949
Telefon Arbeit: 0185 / 55586734 
----------------------------------------
Kann Buttons klicken. 
Kann bei Maschinen die Instandhaltung durchführen.
Kann bei Aufgabenverwaltung To-Do liste einsehen und bearbeiten. 
Kann auf Lager zugreifen und nach Maschinen Filtern. (das nur die Ersatzteile für die Maschine angezeigt werden)
Kann Profil einsehen aber nur PB umändern restliche Daten nicht.

**Comment by randums** [comment]
Profil 2 Daten:
Vorname: Franz
Nachname: Lusitg
Geburtstag: 01.08.1976
E-Mail: franzlustig1976@gmail.com
Telefon Privat: 0196 / 84236437
Telefon Arbeit: 0171 / 87845747
-----------------------------------

Kann keine Buttons klicken.
Kann bei Maschinen nur anklicken und Instandhaltung betrachten um bpsw. die Letze Inspektion nachzuschauen.
Kann bei Aufgabenverwaltung To-Do liste einsehen aber nicht bearbeiten.
Kann auf Lager zugreifen und nach Maschinen Filtern. (das nur die Ersatzteile für die Maschine angezeigt werden)
Kann Profil einsehen aber nur PB umändern restliche Daten nicht.
