### ISSUE TITLE
"Aufgabenverwaltung"/ Task Management

### ISSUE THREAD

**Issue by 100xA** [100xA/IntegrationFlutterApp#5]
+ [ ] Create a Calendar with Tasks for each user 
+ [ ] Connect Tasks with Database (Cloud Firestore)

<img width="381" alt="image" src="https://user-images.githubusercontent.com/24482713/228018462-3d02ad29-232c-4282-9d38-803b3fdd6bed.png">

**Comment by randums** [comment]
Passt Kalender und To-Do Liste reicht. So das man auf den Tag im Kalender drückt und dann die To-Do Liste auf geht. To-Do Liste kann schon was drin stehen kann aber auch selbst bearbeitet werden.
